export const menu = [
  {
    index: 1,
    categoryFrench: "Entrees",
    name: "Salade de chou kale",
    frenchDescription:
      "Avocat, feta, pignons de pain, grenade et pesto traditionnel",
    englishDescription:
      "Kale salad: avocado, feta, pine nuts, pomegranate and traditional pesto",
    price: 29,
    menuMidi: true,
    menuContinue: false,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 1,
    categoryFrench: "",
    name: "",
    frenchDescription: "",
    englishDescription: "",
    price: 16,
    menuMidi: true,
    menuContinue: true,
    menuSoir: false,
    menuBoission: false,
  },
  {
    index: 46,
    categoryFrench: "Focaccias",
    name: "Focaccia",
    frenchDescription: "al prosciutto San daniele",
    price: 14,
    menuMidi: true,
    menuContinue: true,
    menuSoir: false,
    menuBoission: false,
  },
  {
    index: 47,
    categoryFrench: "Focaccias",
    name: "Focaccia di Manu",
    frenchDescription: "Stracciatella di burrata",
    price: 16,
    menuMidi: true,
    menuContinue: true,
    menuSoir: false,
    menuBoission: false,
  },
  {
    index: 48,
    categoryFrench: "Focaccias",
    name: "Focaccia di Fabio",
    frenchDescription: "Roquette, confiture de figues, vinaigre balsamique",
    englishDescription: "Arugula, fig jam, balsamic vinegar",
    price: 16,
    menuMidi: true,
    menuContinue: true,
    menuSoir: false,
    menuBoission: false,
  },

  {
    index: 49,
    categoryFrench: "Desserts",
    frenchDescription: "Assiette de fromages de Savoie",
    englishDescription: "Regional cheese platter",
    price: 14,
    menuMidi: true,
    menuContinue: true,
    menuSoir: false,
    menuBoission: false,
  },
];
