export const menu = [
  {
    index: 0,
    categoryFrench: "Entrees",
    name: "Salade verte",

    englishDescription: "Green salad",
    price: 8,
    menuMidi: false,
    menuContinue: true,
    menuSoir: false,
    menuBoission: false,
  },
  {
    index: 1,
    categoryFrench: "Entrees",
    name: "Salade de chou kale",
    frenchDescription:
      "Avocat, feta, pignons de pain, grenade et pesto traditionnel",
    englishDescription:
      "Kale salad: avocado, feta, pine nuts, pomegranate and traditional pesto",
    price: 29,
    menuMidi: true,
    menuContinue: false,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 2,
    categoryFrench: "Entrees",
    name: "Salade maraîchère",
    frenchDescription:
      "Croûtons à l’ail et sa vinaigrette à l’estragon, chou romanesco, carotte, betterave, radis, artichaut, oignon rouge",
    englishDescription:
      "Maraîchère salad: garlic croûtons, tarragon vinaigrette, romanesco cabbage, carrot, beetroot, radish, artichokes, red onions",
    price: 24,
    menuMidi: true,
    menuContinue: true,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 3,
    categoryFrench: "Entrees",
    name: "Salade Kodiak et sa vinaigrette huile d’olive citron et coriandre",
    frenchDescription: "Crabe, laitue, avocat",
    englishDescription:
      "Kodiak salad: lemon, coriander, olive oil vinaigrette, crabe lettuce, avocado",
    price: 30,
    menuMidi: true,
    menuContinue: false,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 4,
    categoryFrench: "Entrees",
    name: "Salade César « petite » ou « grande »",
    frenchDescription: "Bacon, parmesan, croûtons et sa fameuse sauce",
    englishDescription:
      "Caesar salad « small » « large »: lettuce, bacon, croûtons and the famous sauce",
    price: 14,
    price2: 24,
    menuMidi: true,
    menuContinue: true,
    menuSoir: false,
    menuBoission: false,
  },
  {
    index: 5,
    categoryFrench: "Entrees",
    name: "Chicken César « petite » ou « grande »",
    frenchDescription: "Poulet, parmesan, croûtons et sa fameuse sauce",
    englishDescription:
      "Chicken Caesar salad « small » « large »: chicken, lettuce, bacon, croûtons and the famous sauce",
    price: 19,
    price2: 29,
    menuMidi: true,
    menuContinue: true,
    menuSoir: false,
    menuBoission: false,
  },
  {
    index: 6,
    categoryFrench: "Entrees",
    name: "The goat",
    frenchDescription:
      "Fingers sablés aux fruits secs, chèvre frais et betterave confite",
    englishDescription:
      "The goat: shortbread finger with fresh goat cheese and candied beetroot",
    price: 24,
    menuMidi: false,
    menuContinue: false,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 7,
    categoryFrench: "Entrees",
    name: "Escargots à la douzaine de la ferme de Billième (Savoie)",
    englishDescription: "Snails by the dozen by from the Billième farm",
    price: 24,
    menuMidi: true,
    menuContinue: true,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 8,
    categoryFrench: "Entrees",
    name: "Foie gras pain d’épices, chutney de fruits du moment et sa belle brioche",
    englishDescription:
      "Gingerbread foie gras, fruit chutney of the moment and the great brioche",
    price: 36,
    menuMidi: false,
    menuContinue: false,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 9,
    categoryFrench: "Entrees",
    name: "Burrata crémeuse verdure al forno et assaisonnement huile d’olive citron",
    frenchDescription: "Légumes de saison du moment",
    englishDescription:
      "Creamy burrata, seasonal vegetables and lemon olive oil",
    price: 24,
    menuMidi: true,
    menuContinue: false,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 10,
    categoryFrench: "Entrees",
    name: "Salade niçoise à notre façon",
    frenchDescription:
      "Tomates cerises, poivron, œuf, cébettes, haricots verts, ventrêche de thon, anchois, olives noires, radis, vinaigrette",
    englishDescription:
      "Nicoise salad: cherry tomatoes, bell pepper, egg, spring onion, green beans, tuna belly, anchovies, black olives, radish",
    price: 30,
    menuMidi: true,
    menuContinue: false,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 11,
    categoryFrench: "Entrees",
    name: "Louis Bowl",
    frenchDescription: "Kasha, avocat, mangue, concombre, radis",
    englishDescription:
      "Louis bowl: kasha cereals, avocado, mango, cucumber, radish",
    price: 24,
    suppPrice1Title: "Supplément Saumon",
    suppPrice1: 9,
    suppPrice2Title: "Supplement Thon",
    suppPrice2: 9,
    menuMidi: false,
    menuContinue: true,
    menuSoir: false,
    menuBoission: false,
  },
  {
    index: 12,
    categoryFrench: "Entrees",
    name: "Planche : Charcuterie ou Mixte et ses pickles",

    englishDescription: "Platter: charcuterie or mixed and some pickles",
    price: 24,
    menuMidi: false,
    menuContinue: true,
    menuSoir: false,
    menuBoission: false,
  },

  {
    index: 35,
    categoryFrench: "Pizza",
    name: "MARGARITA",
    frenchDescription: "Tomate, mozzarella",
    englishDescription: "Tomato sauce, mozzarella",
    price: 21,
    menuMidi: true,
    menuContinue: true,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 36,
    categoryFrench: "Pizza",
    name: "DIAVOLA",
    frenchDescription: "Tomate, mozzarella, spianata piccante",
    englishDescription: "Tomato sauce, mozzarella, spicy spianata piccante",
    price: 23,
    menuMidi: true,
    menuContinue: true,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 37,
    categoryFrench: "Pizza",
    name: "REINA",
    frenchDescription:
      "Tomate, mozzarella, champignons, jambon blanc après cuisson",
    englishDescription:
      "Tomato sauce, mozzarella, mushrooms, ham after cooking",
    price: 27,
    menuMidi: true,
    menuContinue: true,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 38,
    categoryFrench: "Pizza",
    name: "NAPOLITANA",
    frenchDescription:
      "Tomate, mozzarella, anchois, olives, câpres, tomates cerises",
    englishDescription:
      "Tomato sauce, mozzarella, anchovies, olives, capers, cherry tomatoes",
    price: 27,
    menuMidi: true,
    menuContinue: true,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 39,
    categoryFrench: "Pizza",
    name: "HAWAÏENNE",
    frenchDescription: "Tomate, mozzarella, ananas, jambon blanc après cuisson",
    englishDescription:
      "Tomato sauce, mozzarella, pineapple, ham after cooking",
    price: 27,
    menuMidi: true,
    menuContinue: true,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 40,
    categoryFrench: "Pizza",
    name: "CAPRESE",
    frenchDescription:
      "Tomate, stracciatella di burrata, basilic, olives noires",
    englishDescription:
      "Tomato sauce, stracciatella di buffala, basil, black olives",
    price: 28,
    menuMidi: true,
    menuContinue: true,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 41,
    categoryFrench: "Pizza",
    name: "ROMANA",
    frenchDescription:
      "Tomate, mozzarella, spianata piccante, poivrons, tomates cerises",
    englishDescription:
      "Tomato sauce, mozzarella, spicy spianata piccante, peppers, cherry tomatoes",
    price: 28,
    menuMidi: true,
    menuContinue: true,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 42,
    categoryFrench: "Pizza",
    name: "TRE FORMAGGI",
    frenchDescription: "Mozzarella, gorgonzola, brézain fumé",
    englishDescription: "Mozzarella, gorgonzola, smoked brézain cheese",
    price: 28,
    menuMidi: true,
    menuContinue: true,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 43,
    categoryFrench: "Pizza",
    name: "ALPAGE",
    frenchDescription: "Mozzarella, reblochon, lardons, oignons",
    englishDescription: "Mozzarella, reblochon cheese, bacon, onions",
    price: 28,
    menuMidi: true,
    menuContinue: true,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 44,
    categoryFrench: "Pizza",
    name: "GIANNI",
    frenchDescription:
      "Mozzarella, prosciutto, tomates cerises, roquette, parmesan, confiture de figues",
    englishDescription:
      "Mozzarella, prosciutto, cherry tomatoes, arugula, parmigiano reggiano, fig jam",
    price: 31,
    menuMidi: true,
    menuContinue: true,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 45,
    categoryFrench: "Pizza",
    name: "PROSCIUTTO",
    frenchDescription:
      "Tomate, mozzarella, prosciutto, tomates cerise, parmesan, roquette",
    englishDescription:
      "omato sauce, mozzarella, prosciutto, cherry tomatoes, parmigiano reggiano, arugula",
    price: 31,
    menuMidi: true,
    menuContinue: true,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 46,
    categoryFrench: "Pizza",
    name: "TARTUFO",
    frenchDescription:
      "Crème tartufi, mozzarella, truffe noire fraîche, œuf bio",
    englishDescription:
      "Mozzarella, tartufi cream, fresh black truffle, organic egg",
    price: 43,
    menuMidi: true,
    menuContinue: true,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 47,
    categoryFrench: "Pizza",
    name: "EMILIANA",
    frenchDescription:
      "Mozzarella, ricotta, mortadelle, pesto de pistache et pistaches concassées, roquette",
    englishDescription:
      "Mozzarella, ricotta, mortadelle, pistachio pesto, crushed pistachio, arugula",
    price: 31,
    menuMidi: true,
    menuContinue: true,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 48,
    categoryFrench: "Pizza",
    name: "VÉGÉTARIENNE",
    frenchDescription:
      "Tomate, mozzarella, artichauts, champignons, tomates cerise, feuilles d’épinard",
    englishDescription:
      "Tomato sauce, mozzarella, artichoke, mushrooms, cherry tomatoes, spinach leaves",
    price: 28,
    menuMidi: true,
    menuContinue: true,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 49,
    categoryFrench: "Pizza",
    name: "VIOLA",
    frenchDescription: "Mozzarella, gorgonzola, chou rouge, olives noires",
    englishDescription: "Mozzarella, gorgonzola, red cabbage, olives",
    price: 31,
    menuMidi: true,
    menuContinue: true,
    menuSoir: true,
    menuBoission: false,
  },

  {
    index: 46,
    categoryFrench: "Focaccias",
    name: "Focaccia",
    frenchDescription: "al prosciutto San daniele",
    price: 14,
    menuMidi: true,
    menuContinue: true,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 47,
    categoryFrench: "Focaccias",
    name: "Focaccia di Manu",
    frenchDescription: "Stracciatella di burrata",
    price: 16,
    menuMidi: true,
    menuContinue: true,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 48,
    categoryFrench: "Focaccias",
    name: "Focaccia di Fabio",
    frenchDescription: "Roquette, confiture de figues, vinaigre balsamique",
    englishDescription: "Arugula, fig jam, balsamic vinegar",
    price: 16,
    menuMidi: true,
    menuContinue: true,
    menuSoir: true,
    menuBoission: false,
  },

  {
    index: 49,
    categoryFrench: "Desserts",
    frenchDescription: "Assiette de fromages de Savoie",
    englishDescription: "Regional cheese platter",
    price: 14,
    menuMidi: true,
    menuContinue: true,
    menuSoir: false,
    menuBoission: false,
  },
];
