export const menu = [
  {
    index: 0,
    categoryFrench: "Entrees",
    name: "Salade verte",
    englishDescription: "Green salad",
    price: 8,
    menuMidi: false,
    menuContinue: true,
    menuSoir: false,
    menuBoission: false,
  },
  {
    index: 1,
    categoryFrench: "Entrees",
    name: "Salade de chou kale",
    frenchDescription:
      "Avocat, feta, pignons de pain, grenade et pesto traditionnel",
    englishDescription:
      "Kale salad: avocado, feta, pine nuts, pomegranate and traditional pesto",
    price: 29,
    menuMidi: true,
    menuContinue: false,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 2,
    categoryFrench: "Entrees",
    name: "Salade maraîchère",
    frenchDescription:
      "Croûtons à l’ail et sa vinaigrette à l’estragon, chou romanesco, carotte, betterave, radis, artichaut, oignon rouge",
    englishDescription:
      "Maraîchère salad: garlic croûtons, tarragon vinaigrette, romanesco cabbage, carrot, beetroot, radish, artichokes, red onions",
    price: 24,
    menuMidi: true,
    menuContinue: true,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 3,
    categoryFrench: "Entrees",
    name: "Salade Kodiak et sa vinaigrette huile d’olive citron et coriandre",
    frenchDescription: "Crabe, laitue, avocat",
    englishDescription:
      "Kodiak salad: lemon, coriander, olive oil vinaigrette, crabe lettuce, avocado",
    price: 30,
    menuMidi: true,
    menuContinue: false,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 4,
    categoryFrench: "Entrees",
    name: "Salade César « petite » ou « grande »",
    frenchDescription: "Bacon, parmesan, croûtons et sa fameuse sauce",
    englishDescription:
      "Caesar salad « small » « large »: lettuce, bacon, croûtons and the famous sauce",
    price: 14,
    price2: 24,
    menuMidi: true,
    menuContinue: true,
    menuSoir: false,
    menuBoission: false,
  },
  {
    index: 5,
    categoryFrench: "Entrees",
    name: "Chicken César « petite » ou « grande »",
    frenchDescription: "Poulet, parmesan, croûtons et sa fameuse sauce",
    englishDescription:
      "Chicken Caesar salad « small » « large »: chicken, lettuce, bacon, croûtons and the famous sauce",
    price: 19,
    price2: 29,
    menuMidi: true,
    menuContinue: true,
    menuSoir: false,
    menuBoission: false,
  },
  {
    index: 6,
    categoryFrench: "Entrees",
    name: "The goat",
    frenchDescription:
      "Fingers sablés aux fruits secs, chèvre frais et betterave confite",
    englishDescription:
      "The goat: shortbread finger with fresh goat cheese and candied beetroot",
    price: 24,
    menuMidi: false,
    menuContinue: false,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 7,
    categoryFrench: "Entrees",
    name: "Escargots à la douzaine de la ferme de Billième (Savoie)",
    englishDescription: "Snails by the dozen by from the Billième farm",
    price: 24,
    menuMidi: true,
    menuContinue: true,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 8,
    categoryFrench: "Entrees",
    name: "Foie gras pain d’épices, chutney de fruits du moment et sa belle brioche",
    englishDescription:
      "Gingerbread foie gras, fruit chutney of the moment and the great brioche",
    price: 36,
    menuMidi: false,
    menuContinue: false,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 9,
    categoryFrench: "Entrees",
    name: "Burrata crémeuse verdure al forno et assaisonnement huile d’olive citron",
    frenchDescription: "Légumes de saison du moment",
    englishDescription:
      "Creamy burrata, seasonal vegetables and lemon olive oil",
    price: 24,
    menuMidi: true,
    menuContinue: false,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 10,
    categoryFrench: "Entrees",
    name: "Salade niçoise à notre façon",
    frenchDescription:
      "Tomates cerises, poivron, œuf, cébettes, haricots verts, ventrêche de thon, anchois, olives noires, radis, vinaigrette",
    englishDescription:
      "Nicoise salad: cherry tomatoes, bell pepper, egg, spring onion, green beans, tuna belly, anchovies, black olives, radish",
    price: 30,
    menuMidi: true,
    menuContinue: false,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 11,
    categoryFrench: "Entrees",
    name: "Louis Bowl",
    frenchDescription: "Kasha, avocat, mangue, concombre, radis",
    englishDescription:
      "Louis bowl: kasha cereals, avocado, mango, cucumber, radish",
    price: 24,
    suppPrice1Title: "Supplément Saumon",
    suppPrice1: 9,
    suppPrice2Title: "Supplement Thon",
    suppPrice2: 9,
    menuMidi: false,
    menuContinue: true,
    menuSoir: false,
    menuBoission: false,
  },
  {
    index: 12,
    categoryFrench: "Entrees",
    name: "Planche : Charcuterie ou Mixte et ses pickles",

    englishDescription: "Platter: charcuterie or mixed and some pickles",
    price: 24,
    menuMidi: false,
    menuContinue: true,
    menuSoir: false,
    menuBoission: false,
  },

  {
    index: 13,
    categoryFrench: "Antipasti",
    name: "Tartine aux cèpes gratinée au Beaufort",
    englishDescription: "Porcini mushrooms and Beaufort cheese toasted bread",
    price: 30,
    menuMidi: true,
    menuContinue: false,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 14,
    categoryFrench: "Antipasti",
    name: "Tresse de mozzarella, grappes de tomates cerises et amandes torréfiées",
    englishDescription:
      "Braid of mozzarella, bunches of cherry tomatoes and roasted almonds",
    price: 29,
    menuMidi: true,
    menuContinue: false,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 15,
    categoryFrench: "Antipasti",
    name: "Duo de focaccia di Fabio Prosciutto et stracciatella",
    englishDescription:
      "Duo of focaccia di Fabio: one with prosciutto and the other with stracciatella",
    price: 25,
    menuMidi: true,
    menuContinue: false,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 16,
    categoryFrench: "Antipasti",
    name: "Berrichon et confiture de figues",
    frenchDescription:
      "Crottin de chèvre en chausson, oignons confits, mesclun, noix, confiture de figues",
    englishDescription:
      "Kind of a goat cheese salad on a pizza base with onions, fig jam and nuts",
    price: 30,
    menuMidi: true,
    menuContinue: false,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 17,
    categoryFrench: "Antipasti",
    name: "Verdure al forno",
    frenchDescription: "Légumes de saison du moment",
    englishDescription: "Seasonal vegetables",
    vegan: true,
    price: 17,
    menuMidi: true,
    menuContinue: false,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 18,
    categoryFrench: "Antipasti",
    name: "Planche",
    frenchDescription: "Charcuterie ou mixte et ses pickles",
    englishDescription: "Platter: charcuterie or mixed and some pickles",
    price: 24,
    menuMidi: true,
    menuContinue: false,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 19,
    categoryFrench: "Antipasti",
    name: "Pissaladière « La Face »",
    frenchDescription: "Oignons confits, olives noires, anchois",
    englishDescription:
      "Pissaladière « La Face »: onions, black olives, anchovies",
    price: 29,
    menuMidi: true,
    menuContinue: false,
    menuSoir: true,
    menuBoission: false,
  },

  {
    index: 20,
    categoryFrench: "Soupes",
    name: "Soupe à l’oignon",
    frenchDescription: "Croûtons et Beaufort",
    englishDescription: "Onion soup: croûtons and Beaufort cheese",
    price: 17,
    menuMidi: true,
    menuContinue: true,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 21,
    categoryFrench: "Soupes",
    name: "Soupe du moment et ses condiments",
    englishDescription: "Soup of the moment",
    price: 16,
    menuMidi: true,
    menuContinue: true,
    menuSoir: true,
    menuBoission: false,
  },

  {
    index: 22,
    categoryFrench: "Pates",
    name: "Lasagnes au bœuf fondant",
    englishDescription: "Lasagna",
    price: 29,
    menuMidi: true,
    menuContinue: false,
    menuSoir: false,
    menuBoission: false,
  },
  {
    index: 23,
    categoryFrench: "Pates",
    name: "Gnocchis aux truffes",
    frenchDescription:
      "À la crème truffée, pétales de parmigiano reggiano et truffes fraîches",
    englishDescription:
      "Gnocchis served with fresh black truffles and parmigiano reggiano",
    price: 48,
    menuMidi: true,
    menuContinue: false,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 24,
    categoryFrench: "Pates",
    name: "Macaronis al verdure al forno e parmigiano reggiano",
    englishDescription:
      "Pasta macaroni served with seasonal vegetables and parmigiano reggiano",
    price: 30,
    menuMidi: true,
    menuContinue: false,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 25,
    categoryFrench: "Pates",
    name: "Tagliatelles au king crab et bisque crémeuse",
    englishDescription: "King crab tagliatelle and creamy bisque",
    price: 46,
    menuMidi: true,
    menuContinue: false,
    menuSoir: true,
    menuBoission: false,
  },

  {
    index: 26,
    categoryFrench: "Plats",
    name: "Lasagnes au bœuf fondant",
    englishDescription: "Lasagna",
    price: 29,
    menuMidi: false,
    menuContinue: true,
    menuSoir: false,
    menuBoission: false,
  },
  {
    index: 27,
    categoryFrench: "Plats",
    name: "Hot-dog « La Face »",
    frenchDescription:
      "Saucisse de bœuf, chou, lard, oignon frit, cébettes, ketchup, moutarde au miel",
    englishDescription:
      "« The Face » Hot dog: beef sausage, cabbage, bacon, fried onions, ketchup, honey mustard",
    price: 18,
    suppPriceTitle: "Supplément frites",
    suppPrice1: 2,
    menuMidi: false,
    menuContinue: true,
    menuSoir: false,
    menuBoission: false,
  },
  {
    index: 28,
    categoryFrench: "Plats",
    name: "Hot-dog « Crevette »",
    frenchDescription: "choux, carotte, soja, sauce aigre douce, cacahuète",
    englishDescription:
      "Shrimp hot dog: cabbage, carrot, soja, sweet and sour sauce, peanut",
    price: 17,
    suppPriceTitle: "Supplément frites",
    suppPrice1: 2,
    menuMidi: false,
    menuContinue: true,
    menuSoir: false,
    menuBoission: false,
  },
  {
    index: 29,
    categoryFrench: "Plats",
    name: "Club sandwich Reuben",
    frenchDescription:
      "Pain, bœuf, choucroute, mayonnaise, moutarde à l’ancienne et cornichons",
    englishDescription:
      "Reuben club sandwich: bread, beef, sauerkraut, mayonnaise, old style mustard and pickles",
    price: 19,
    suppPriceTitle: "Supplément frites",
    suppPrice1: 2,
    menuMidi: false,
    menuContinue: true,
    menuSoir: false,
    menuBoission: false,
  },

  {
    index: 30,
    categoryFrench: "Viandes",
    name: "Côte de veau Metzger Frères",
    frenchDescription:
      "Duo de champignons aillés persillés et écrasé de pommes de terre",
    englishDescription:
      "Veal rib with a duo of parsley garlic mushrooms and mashed potatoes",
    price: 52,
    menuMidi: true,
    menuContinue: false,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 31,
    categoryFrench: "Viandes",
    name: "Suprême de pintade aux écrevisses",
    frenchDescription: "Gnocchis et chou romanesco",
    englishDescription:
      "Guinea fowl suprême with grayfish: gnocchi and romanesco cabbage",
    price: 51,
    menuMidi: false,
    menuContinue: false,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 32,
    categoryFrench: "Viandes",
    name: "Filet d’agneau persillé et artichauts en deux textures",
    frenchDescription: "Mousseline d’artichauts, artichaut poivrade et chips",
    englishDescription:
      "Parsleyed lamb fillet and artichoke in two textures: artichoke mousseline, poivrade artichoke and chips",
    price: 49,
    menuMidi: false,
    menuContinue: false,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 33,
    categoryFrench: "Viandes",
    name: "Côte de bœuf Salers Metzger Frères",
    frenchDescription: "Maturée 8 semaines (+/- 500 gr), frites",
    englishDescription:
      "Beef rib steak matured 8 weeks Metzger Frères Paris (+-500gr), French fries",
    price: 58,
    menuMidi: true,
    menuContinue: false,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 34,
    categoryFrench: "Viandes",
    name: "Côte de porc Ibérique Metzger Frères",
    frenchDescription:
      "Frites de polenta, crème de maïs et pop corn au piment d’Espelette",
    englishDescription:
      "Pork chop: polenta fries, corn cream and Espelette pepper popcorn",
    price: 39,
    menuMidi: false,
    menuContinue: false,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 35,
    categoryFrench: "Viandes",
    name: "Tagliata di manzo",
    frenchDescription:
      "Fines tranches de bœuf Metzger Frères, roquette, parmigiano reggiano, pignons de pain",
    englishDescription:
      "Tagliata di manzo: thin slices of Metzger Frères beef, arugula, parmigiano reggiano, pine nuts",
    price: 49,
    menuMidi: false,
    menuContinue: false,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 36,
    categoryFrench: "Viandes",
    name: "Tartare de bœuf",
    frenchDescription: "Préparé, roquette, parmesan, frites",
    englishDescription:
      "Tartar: prepared (+-200gr), arugula, parmigiano reggiano, French fries",
    price: 32,
    menuMidi: true,
    menuContinue: false,
    menuSoir: false,
    menuBoission: false,
  },
  {
    index: 37,
    categoryFrench: "Viandes",
    name: "Chicken Schnitzel",
    frenchDescription:
      "Filet de poulet français frit, écrasé de pommes de terre, gelée de groseilles et sauce Brézain",
    englishDescription:
      "Chicken schnitzel: French chicken, cream cheese, currant jelly, mashed potatoes",
    price: 34,
    menuMidi: true,
    menuContinue: false,
    menuSoir: true,
    menuBoission: false,
  },

  {
    index: 38,
    categoryFrench: "Poissons",
    name: "Dos de cabillaud",
    frenchDescription: "Légumes de saison et fumet de poisson à la citronnelle",
    englishDescription:
      "Cod fillet: seasonal vegetables and lemongrass fish stock",
    price: 39,
    menuMidi: true,
    menuContinue: false,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 39,
    categoryFrench: "Poissons",
    name: "Louis Bowl",
    frenchDescription: "Kasha, avocat, mangue, concombre, radis",
    englishDescription:
      "Louis bowl: kasha cereals, avocado, mango, cucumber, radish",
    price: 24,
    suppPrice1Title: "Supplément Saumon",
    suppPrice1: 9,
    suppPrice2Title: "Supplement Thon",
    suppPrice2: 9,
    menuMidi: false,
    menuContinue: true,
    menuSoir: false,
    menuBoission: false,
  },

  {
    index: 40,
    categoryFrench: "Trad",
    name: "Fondue savoyarde du cœur des Bauges, charcuterie",
    frenchDescription: "(pour une personne)",
    englishDescription: "Cheese fondue served with charcuterie (for 1 person)",
    price: 34,
    menuMidi: true,
    menuContinue: false,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 41,
    categoryFrench: "Trad",
    name: "Fondue savoyarde aux cèpes du cœur des Bauges, charcuterie",
    frenchDescription: "(pour une personne)",
    englishDescription:
      "Porcini mushrooms cheese fondue served with charcuterie (for one person)",
    price: 38,
    menuMidi: true,
    menuContinue: false,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 42,
    categoryFrench: "Trad",
    name: "Tartiflette aux truffes",
    frenchDescription: "Pommes de terre, oignons, lard fumé, reblochon",
    englishDescription:
      "Truffles tartiflette: Potatoes, onions, smocked bacon, reblochon cheese",
    price: 24,
    menuMidi: false,
    menuContinue: false,
    menuSoir: true,
    menuBoission: false,
  },

  {
    index: 43,
    categoryFrench: "Pizza",
    name: "MARGARITA",
    frenchDescription: "Tomate, mozzarella",
    englishDescription: "Tomato sauce, mozzarella",
    price: 21,
    menuMidi: true,
    menuContinue: true,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 44,
    categoryFrench: "Pizza",
    name: "DIAVOLA",
    frenchDescription: "Tomate, mozzarella, spianata piccante",
    englishDescription: "Tomato sauce, mozzarella, spicy spianata piccante",
    price: 23,
    menuMidi: true,
    menuContinue: true,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 45,
    categoryFrench: "Pizza",
    name: "REINA",
    frenchDescription:
      "Tomate, mozzarella, champignons, jambon blanc après cuisson",
    englishDescription:
      "Tomato sauce, mozzarella, mushrooms, ham after cooking",
    price: 27,
    menuMidi: true,
    menuContinue: true,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 46,
    categoryFrench: "Pizza",
    name: "NAPOLITANA",
    frenchDescription:
      "Tomate, mozzarella, anchois, olives, câpres, tomates cerises",
    englishDescription:
      "Tomato sauce, mozzarella, anchovies, olives, capers, cherry tomatoes",
    price: 27,
    menuMidi: true,
    menuContinue: true,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 47,
    categoryFrench: "Pizza",
    name: "HAWAÏENNE",
    frenchDescription: "Tomate, mozzarella, ananas, jambon blanc après cuisson",
    englishDescription:
      "Tomato sauce, mozzarella, pineapple, ham after cooking",
    price: 27,
    menuMidi: true,
    menuContinue: true,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 48,
    categoryFrench: "Pizza",
    name: "CAPRESE",
    frenchDescription:
      "Tomate, stracciatella di burrata, basilic, olives noires",
    englishDescription:
      "Tomato sauce, stracciatella di buffala, basil, black olives",
    price: 28,
    menuMidi: true,
    menuContinue: true,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 49,
    categoryFrench: "Pizza",
    name: "ROMANA",
    frenchDescription:
      "Tomate, mozzarella, spianata piccante, poivrons, tomates cerises",
    englishDescription:
      "Tomato sauce, mozzarella, spicy spianata piccante, peppers, cherry tomatoes",
    price: 28,
    menuMidi: true,
    menuContinue: true,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 50,
    categoryFrench: "Pizza",
    name: "TRE FORMAGGI",
    frenchDescription: "Mozzarella, gorgonzola, brézain fumé",
    englishDescription: "Mozzarella, gorgonzola, smoked brézain cheese",
    price: 28,
    menuMidi: true,
    menuContinue: true,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 51,
    categoryFrench: "Pizza",
    name: "ALPAGE",
    frenchDescription: "Mozzarella, reblochon, lardons, oignons",
    englishDescription: "Mozzarella, reblochon cheese, bacon, onions",
    price: 28,
    menuMidi: true,
    menuContinue: true,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 52,
    categoryFrench: "Pizza",
    name: "GIANNI",
    frenchDescription:
      "Mozzarella, prosciutto, tomates cerises, roquette, parmesan, confiture de figues",
    englishDescription:
      "Mozzarella, prosciutto, cherry tomatoes, arugula, parmigiano reggiano, fig jam",
    price: 31,
    menuMidi: true,
    menuContinue: true,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 53,
    categoryFrench: "Pizza",
    name: "PROSCIUTTO",
    frenchDescription:
      "Tomate, mozzarella, prosciutto, tomates cerise, parmesan, roquette",
    englishDescription:
      "omato sauce, mozzarella, prosciutto, cherry tomatoes, parmigiano reggiano, arugula",
    price: 31,
    menuMidi: true,
    menuContinue: true,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 54,
    categoryFrench: "Pizza",
    name: "TARTUFO",
    frenchDescription:
      "Crème tartufi, mozzarella, truffe noire fraîche, œuf bio",
    englishDescription:
      "Mozzarella, tartufi cream, fresh black truffle, organic egg",
    price: 43,
    menuMidi: true,
    menuContinue: true,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 55,
    categoryFrench: "Pizza",
    name: "EMILIANA",
    frenchDescription:
      "Mozzarella, ricotta, mortadelle, pesto de pistache et pistaches concassées, roquette",
    englishDescription:
      "Mozzarella, ricotta, mortadelle, pistachio pesto, crushed pistachio, arugula",
    price: 31,
    menuMidi: true,
    menuContinue: true,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 56,
    categoryFrench: "Pizza",
    name: "VÉGÉTARIENNE",
    frenchDescription:
      "Tomate, mozzarella, artichauts, champignons, tomates cerise, feuilles d’épinard",
    englishDescription:
      "Tomato sauce, mozzarella, artichoke, mushrooms, cherry tomatoes, spinach leaves",
    price: 28,
    menuMidi: true,
    menuContinue: true,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 57,
    categoryFrench: "Pizza",
    name: "VIOLA",
    frenchDescription: "Mozzarella, gorgonzola, chou rouge, olives noires",
    englishDescription: "Mozzarella, gorgonzola, red cabbage, olives",
    price: 31,
    menuMidi: true,
    menuContinue: true,
    menuSoir: true,
    menuBoission: false,
  },

  {
    index: 58,
    categoryFrench: "Focaccias",
    name: "Focaccia",
    frenchDescription: "al prosciutto San daniele",
    price: 14,
    menuMidi: true,
    menuContinue: true,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 59,
    categoryFrench: "Focaccias",
    name: "Focaccia di Manu",
    frenchDescription: "Stracciatella di burrata",
    price: 16,
    menuMidi: true,
    menuContinue: true,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 60,
    categoryFrench: "Focaccias",
    name: "Focaccia di Fabio",
    frenchDescription: "Roquette, confiture de figues, vinaigre balsamique",
    englishDescription: "Arugula, fig jam, balsamic vinegar",
    price: 16,
    menuMidi: true,
    menuContinue: true,
    menuSoir: true,
    menuBoission: false,
  },

  {
    index: 60,
    categoryFrench: "Enfants",
    name: "Mini pizza jambon, fromage",
    englishDescription: "Mini pizza: tomato sauce, mozzarella, ham",
    price: 13.5,
    menuMidi: true,
    menuContinue: false,
    menuSoir: false,
    menuBoission: false,
  },
  {
    index: 61,
    categoryFrench: "Enfants",
    name: "Steak haché, frites",
    englishDescription: "Chopped steak & French fries",
    price: 13.5,
    menuMidi: true,
    menuContinue: false,
    menuSoir: false,
    menuBoission: false,
  },

  {
    index: 62,
    categoryFrench: "Enfants",
    name: "Jambon, frites",
    englishDescription: "Slices of ham & French fries",
    price: 13.5,
    menuMidi: true,
    menuContinue: false,
    menuSoir: false,
    menuBoission: false,
  },

  {
    index: 64,
    categoryFrench: "Desserts",
    name: "Assiette de fromages de Savoie",
    englishDescription: "Regional cheese platter",
    price: 14,
    menuMidi: true,
    menuContinue: true,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 65,
    categoryFrench: "Desserts",
    name: "Vieux gouda accompagné de sa confiture de prunes et d’un verre de vin blanc d’Arbois",
    englishDescription:
      "Aged gouda served with plum jam and a glass of Arbois white wine",
    price: 15,
    menuMidi: true,
    menuContinue: true,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 66,
    categoryFrench: "Desserts",
    name: "Stilton accompagné de sa confiture de poires et d’un verre de Porto rouge",
    englishDescription: "Stilton with pear jam and a glass of Porto",
    price: 15,
    menuMidi: true,
    menuContinue: true,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 67,
    categoryFrench: "Desserts",
    name: "Affogato : Boule de glace vanille noyé dans un expresso",
    englishDescription: "Vanilla ice cream dropped in an expresso",
    price: 8,
    menuMidi: true,
    menuContinue: true,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 68,
    categoryFrench: "Desserts",
    name: "Café gola : Café et une gourmandise du moment",
    englishDescription: "A coffee with a delicacy of the moment",
    price: 9,
    menuMidi: true,
    menuContinue: true,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 69,
    categoryFrench: "Desserts",
    name: "Tartelette chocolat orange",
    englishDescription: "Orange, chocolate tartlet",
    price: 13,
    menuMidi: true,
    menuContinue: true,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 70,
    categoryFrench: "Desserts",
    name: "Paris-Brest",
    englishDescription: "The famous Paris-Brest",
    price: 12,
    menuMidi: true,
    menuContinue: true,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 71,
    categoryFrench: "Desserts",
    name: "Cheesecake caramel au beurre salé",
    englishDescription: "Salted butter caramel cheese cake",
    price: 12,
    menuMidi: true,
    menuContinue: true,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 72,
    categoryFrench: "Desserts",
    name: "Roulé pistache framboise",
    englishDescription: "Raspberry pistacchio roll",
    price: 13,
    menuMidi: true,
    menuContinue: true,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 73,
    categoryFrench: "Desserts",
    name: "Tiramisu",
    englishDescription: "Tiramisu",
    price: 12,
    menuMidi: true,
    menuContinue: true,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 74,
    categoryFrench: "Desserts",
    name: "Mont-Blanc et compotée de myrtilles",
    englishDescription: "Montblanc and blueberry compote",
    price: 13,
    menuMidi: true,
    menuContinue: true,
    menuSoir: true,
    menuBoission: false,
  },
  {
    index: 75,
    categoryFrench: "Desserts",
    name: "Pavlova fruits rouges",
    englishDescription: "Red fruit Pavlova",
    price: 12,
    menuMidi: true,
    menuContinue: true,
    menuSoir: true,
    menuBoission: false,
  },

  {
    index: 76,
    categoryFrench: "Crepes",
    name: "Sucre",
    englishDescription: "Sugar",
    price: 7.3,
    menuMidi: false,
    menuContinue: true,
    menuSoir: false,
    menuBoission: false,
  },
  {
    index: 77,
    categoryFrench: "Crepes",
    name: "Nutella",
    price: 8.2,
    menuMidi: false,
    menuContinue: true,
    menuSoir: false,
    menuBoission: false,
  },
  {
    index: 78,
    categoryFrench: "Crepes",
    name: "Citron",
    englishDescription: "Lemon",
    price: 7.5,
    menuMidi: false,
    menuContinue: true,
    menuSoir: false,
    menuBoission: false,
  },
  {
    index: 79,
    categoryFrench: "Crepes",
    name: "Confiture : fraise, abricot, myrtille",
    englishDescription: "Strawberry, apricot, blueberry",
    price: 7.5,
    menuMidi: false,
    menuContinue: true,
    menuSoir: false,
    menuBoission: false,
  },
  {
    index: 80,
    categoryFrench: "Crepes",
    name: "Miel",
    englishDescription: "Honey",
    price: 7.6,
    menuMidi: false,
    menuContinue: true,
    menuSoir: false,
    menuBoission: false,
  },
  {
    index: 81,
    categoryFrench: "Crepes",
    name: "Chantilly",
    englishDescription: "Whipped cream",
    price: 7.7,
    menuMidi: false,
    menuContinue: true,
    menuSoir: false,
    menuBoission: false,
  },
  {
    index: 82,
    categoryFrench: "Crepes",
    name: "Crème de marrons",
    englishDescription: "Chestnut cream",
    price: 7.7,
    menuMidi: false,
    menuContinue: true,
    menuSoir: false,
    menuBoission: false,
  },
  {
    index: 83,
    categoryFrench: "Crepes",
    name: "Chocolat",
    englishDescription: "Black chocolate",
    price: 7.7,
    menuMidi: false,
    menuContinue: true,
    menuSoir: false,
    menuBoission: false,
  },
  {
    index: 84,
    categoryFrench: "Crepes",
    name: "Sirop d’érable",
    englishDescription: "Maple syrup",
    price: 8.6,
    menuMidi: false,
    menuContinue: true,
    menuSoir: false,
    menuBoission: false,
  },
  {
    index: 85,
    categoryFrench: "Crepes",
    name: "Vanoise : Chocolat, chantilly",
    englishDescription: "Black chocolate, whipped cream",
    price: 9.9,
    menuMidi: false,
    menuContinue: true,
    menuSoir: false,
    menuBoission: false,
  },
  {
    index: 86,
    categoryFrench: "Crepes",
    name: "La Face : Chocolat, banane, chantilly",
    englishDescription: "Black chocolate, banana whipped cream",
    price: 10.3,
    menuMidi: false,
    menuContinue: true,
    menuSoir: false,
    menuBoission: false,
  },
  {
    index: 87,
    categoryFrench: "Crepes",
    name: "Gianni : Nutella, banane, chantilly",
    englishDescription: "Nutella, banana, whipped cream",
    price: 10.6,
    menuMidi: false,
    menuContinue: true,
    menuSoir: false,
    menuBoission: false,
  },

  {
    index: 88,
    categoryFrench: "Glaces",
    name: "Coupe 1 boule au choix",
    price: 5,
    menuMidi: false,
    menuContinue: true,
    menuSoir: false,
    menuBoission: false,
  },
  {
    index: 89,
    categoryFrench: "Glaces",
    name: "Coupe 2 boules au choix",
    suppPrice1: 6.5,
    menuMidi: false,
    menuContinue: true,
    menuSoir: false,
    menuBoission: false,
  },
  {
    index: 90,
    categoryFrench: "Glaces",
    name: "Coupe 3 boules au choix",
    price: 7,
    suppPriceTitle: "Supplément chantilly",
    suppPrice1: 1.5,
    menuMidi: false,
    menuContinue: true,
    menuSoir: false,
    menuBoission: false,
  },

  {
    index: 91,
    categoryFrench: "Snack",
    name: "Frites",
    englishDescription: "French fries",
    price: 7,
    menuMidi: false,
    menuContinue: true,
    menuSoir: false,
    menuBoission: false,
  },
  {
    index: 92,
    categoryFrench: "Snack",
    name: "Sandwich jambon, fromage, beurre, cornichon",
    englishDescription: "Ham, cheese, butter, pickles sandwich",
    price: 9,
    menuMidi: false,
    menuContinue: true,
    menuSoir: false,
    menuBoission: false,
  },
  {
    index: 93,
    categoryFrench: "Snack",
    name: "Sandwich Fromage, beurre",
    englishDescription: "Cheese, butter sandwich",
    price: 7,
    menuMidi: false,
    menuContinue: true,
    menuSoir: false,
    menuBoission: false,
  },
  {
    index: 91,
    categoryFrench: "Snack",
    name: "Sandwich Jambon, beurre",
    englishDescription: "Ham, butter sandwich",
    price: 7,
    menuMidi: false,
    menuContinue: true,
    menuSoir: false,
    menuBoission: false,
  },
  {
    index: 91,
    categoryFrench: "Snack",
    name: "Tartine Croûton Savoyard",
    frenchDescription: "Jambon cru, fromage à raclette toasté",
    englishDescription: "Savoyard toast: regional ham, raclette cheese toasted",
    price: 13,
    menuMidi: false,
    menuContinue: true,
    menuSoir: false,
    menuBoission: false,
  },
];
